### ISSUE TITLE
[Review] *.d.ts を特定ディレクトリに集約する

### ISSUE THREAD

**Issue by Guvalif** [hibimosaku/buy-list#1]
例えば以下のファイルが `src` 以下にそのまま配置されていますが、型定義のみに関連するファイルのため、一箇所に集めると良いかと思います
https://github.com/hibimosaku/buy-list/blob/master/src/shims-vue.d.ts

**Comment by hibimosaku** [comment]
この話、ものすごく学びたい（教えてほしい）です。
現状、これを書かないとエラーでるため、書いたぐらいの知識レベルです。
アンビエンド型宣言？グローバルに利用できる型。
これをどう利用するのかが分かっていません。

また、issue#14(vuexの型）でもこの話がかかわっていますが、コードを書くとエラーがでてまして、未解決です。

**Comment by hibimosaku** [comment]
typesフォルダにまとめておく

**Comment by hibimosaku** [comment]
フォルダ作成して、shims-vue.d.tsを入れたのでクローズします。
commit名：-m'#issue1 typesフォルダ作成'

**Comment by hibimosaku** [comment]
フォルダ作成して、shims-vue.d.tsを入れたのでクローズします。
commit名：-m'#issue1 typesフォルダ作成'

**Comment by hibimosaku** [comment]
shims.vue-d.tsをもとにもどしわすれていたので、戻しました。
commit名：#issu1 shims.vue-d.ts修正
