### ISSUE TITLE
[Review] Model のコードに UseCase が紛れ込んでいる

### ISSUE THREAD

**Issue by Guvalif** [hibimosaku/buy-list#10]
別途 UseCase のファイルを作成しているようなので、そちらにまとめるのが良いかと思います
https://github.com/hibimosaku/buy-list/blob/master/src/model/buy-info.model.ts#L44-L50

**Comment by hibimosaku** [comment]
modelの中に`function changeItemNameUc`とUcをつけたのが誤りでした。
修正して、コミットしました（名：buy-info.model修正 issue#10）

**Comment by hibimosaku** [comment]
上記のとおり修正しましたので、クローズします。
