### ISSUE TITLE
[Review] UseCase が Store に直に依存することが気になる

### ISSUE THREAD

**Issue by Guvalif** [hibimosaku/buy-list#12]
今回の構成だと、UseCase を呼び出す箇所は Actions に限定されているかと思います

Actions は Context を介して `dispatch` や `commit` を使うことができるので、UseCase にも引数経由で Context を渡してあげると良いかと思います

https://github.com/hibimosaku/buy-list/blob/master/src/model/item.use-case.ts

**Comment by hibimosaku** [comment]
仰るとおりです。
修正します。

**Comment by hibimosaku** [comment]
修正しました。#6,7修正のときに

**Comment by hibimosaku** [comment]
上記のとおり修正しましたので、クローズします
