### ISSUE TITLE
[Review] container と component 以外の箇所にある *.vue の責務が不明瞭

### ISSUE THREAD

**Issue by Guvalif** [hibimosaku/buy-list#13]
view 内にそのまま置かれている `*.vue` が、なぜ Container Component ではないかが不明瞭かと思いました (何か理由があるのであれば、それで問題ありません)

https://github.com/hibimosaku/buy-list/tree/master/src/view

**Comment by hibimosaku** [comment]
以下のルールにより分けています。
・view内にそのまま置いているファイル
　親コンポーネント、メインUI画面
・部品ファイル
　- component
　　vuex,propsデータのないコンポーネント→要修正
　- container
　　vuex,propsデータを持つコンポーネント→要修正

**Comment by hibimosaku** [comment]
パターンがある
pages相当。pages、サブcomponent。
buy-listフォルダ→components,containes

**Comment by hibimosaku** [comment]
修正しました。
commit名：issu#13 フォルダ構成修正

**Comment by hibimosaku** [comment]
修正しました。
commit名：issu#13 フォルダ構成修正
