### ISSUE TITLE
[Review] 各 *.vue で直接 Store を参照している

### ISSUE THREAD

**Issue by Guvalif** [hibimosaku/buy-list#14]
Vuex の場合、初期化時に全ての Component に対して `this` を経由した Store へのアクセスを許可することができます
**s.a.** https://vuex.vuejs.org/ja/guide/state.html#%E5%8D%98%E4%B8%80%E3%82%B9%E3%83%86%E3%83%BC%E3%83%88%E3%83%84%E3%83%AA%E3%83%BC

これを用いることで、各 Component が直接 Store に依存することを防ぐことができます

**Comment by hibimosaku** [comment]
すべきことは理解（this.$store作成）したが、
現状、以下情報をもとに作成しようとしたが、エラーでうまくいかず、保留。
「Vuexは、すぐに使用できるthis.$storeプロパティの入力を提供していません。TypeScriptで使用する場合は、独自のモジュール拡張を宣言する必要があります。」
https://next.vuex.vuejs.org/guide/typescript-support.html#typing-store-property-in-vue-component

【失敗】
・`this.$store.commit("changeCategoryStore"`→`Property '$store' does not exist on type 'void'.`
・`shims-vue.d.ts`の実装が必要だが、$storeの定義を書くとエラーがでる。
コメントアウト部分がエラーになる。
```ts:shims-vue.d.ts
/* eslint-disable */

// import { DefineComponent } from "vue";

declare module "*.vue" {
  import type { DefineComponent } from "vue";
  import { Store } from "vuex";
  // import { State } from "./store/store";

  const component: DefineComponent<{}, {}, any>;
  export default component;
  // interface Vue {
    
    // $store: Store<void>, // Store が any になっているのでこの部分は妥協する
    // $state: State // State はこうすることによって型定義が守られる
  // }
  // interface ComponentCustomProperties {
  //   $store: Store<any>
  // }
}
// import { Store } from "vuex";
// import { State } from "./store/store";

// declare module '@vue/runtime-core' {
  // declare your own store states

  // provide typings for `this.$store`
//   interface ComponentCustomProperties {
//     $store: Store<State>
//   }
// }
```
![image](https://user-images.githubusercontent.com/47348031/150654361-1f2cb5f6-0e17-4ecd-ae5e-1b9baada468a.png)

**Comment by hibimosaku** [comment]
以下のとおり修正してクローズ
commit名：issue#14 直接Stor→useStoreに変更

変更前` import { store } from "../store/store"; `
↓
変更後` import { useStore } from 'vuex' `

https://next.vuex.vuejs.org/guide/composition-api.html

**Comment by hibimosaku** [comment]
クローズしたが、エラー発生。
` useStore ` がundifiend状態

**Comment by hibimosaku** [comment]
以下入力で解決

store.ts
```
import { useStore  as _useStore } from "vuex";

export function useStore(){
  return _useStore(key)
}
```

各.vue
```
<script lang="ts">
import { useStore } from "../../store/store"
const store = useStore()
```
