### ISSUE TITLE
[Review] vue-router に名前つきルートとそうでないルートが混在している

### ISSUE THREAD

**Issue by Guvalif** [hibimosaku/buy-list#2]
おそらく、`<router-link>` Component でリンクしているか，していないかで分けているとは思いますが、いっそ一律で付与するでも問題ない気もします
https://github.com/hibimosaku/buy-list/blob/master/src/router/router.ts

**s.a.** https://router.vuejs.org/ja/guide/essentials/named-routes.html

**Comment by hibimosaku** [comment]
仰るとおりです。
修正しました。
commit名：vue-routerに名前付与 issue#2

**Comment by hibimosaku** [comment]
上記のとおり修正したため、クローズします。
