### ISSUE TITLE
[Review] Actions で直に Context 内部の State を操作している

### ISSUE THREAD

**Issue by Guvalif** [hibimosaku/buy-list#5]
Mutations は State の直接操作することを許容しますが、通常 Actions が State を直接操作するのはアンチパターンです (`modules` 以下の Store に関しても同様です)
https://github.com/hibimosaku/buy-list/blob/master/src/store/store.ts#L20-L39

あくまで、Actions では commit だけ行うと良いかと思います
**s.a.** https://vuex.vuejs.org/ja/guide/actions.html#%E3%82%A2%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AE%E3%83%86%E3%82%99%E3%82%A3%E3%82%B9%E3%83%8F%E3%82%9A%E3%83%83%E3%83%81

**Comment by hibimosaku** [comment]
修正します！

**Comment by hibimosaku** [comment]
修正しました。
actionのstate処理→mutationへ issu#5
以下は一例ですが、
#7内容（Mutations には純粋な状態変更しか記述しないことがベストプラクティス） も含めて、
state部分だけ記述した形にしています。
【mutations】
```
  changeBuyRequestDoStore(
    state: State,
    data: { key: number; request: boolean }
  ) {
    state.BuyInfoList[data.key].buyRequest = data.request;
  },
```
【actions】
```
  async changeBuyRequestDoStore(
    context: { state: State; commit: Commit },
    data: {
      buyInfoId: ID;
      request: boolean;
      uid: string;
    }
  ) {
    context.state.BuyInfoList.forEach((v, k) => {
      if (v.buyInfoId === data.buyInfoId) {
        BuyInfoUseCase.changeBuyRequestUc(v, data.request, data.uid)
          .then(() => {
            context.commit("changeBuyRequestDoStore", {
              key: k,
              request: data.request,
            });
          })
          .catch(() => {
            return;
          });
      }
    });
  },

```

**Comment by hibimosaku** [comment]
上記のとおり修正しましたので、クローズします
