### ISSUE TITLE
[Review] Mutations に非同期処理 ≒ 副作用が混入している

### ISSUE THREAD

**Issue by Guvalif** [hibimosaku/buy-list#7]
Vuex においては、Actions に UseCase の処理を集約し、Mutations には純粋な状態変更しか記述しないことがベストプラクティスかと思います (`modules` 以下の Store に関しても同様です)
https://github.com/hibimosaku/buy-list/blob/master/src/store/modules/buy-info-store.ts#L32-L36

**Comment by hibimosaku** [comment]
ActionsにUsecaseの処理を集約します。
いままで、actionとmutationsの使い分けに答えがなかったので、
パターンとして学べてよかったです。

**Comment by hibimosaku** [comment]
store,category済

**Comment by hibimosaku** [comment]
mutations→actions
・deleteItemStoreでうまくいかず
　処理は出来ているが、即反映（表示から消える）がうまくいかない。
　- リロードしたら反映される。
　- mutationsでの処理は即反映できている

**Comment by hibimosaku** [comment]
修正しました。
commit名：Mutations に非同期処理 ≒ 副作用が混入しているissue#7

**Comment by hibimosaku** [comment]
上記のとおり修正しましたのでクローズします
