### ISSUE TITLE
[Review] ID から ValueObject の型が消えてしまっている

### ISSUE THREAD

**Issue by Guvalif** [hibimosaku/buy-list#9]
`buyInfoId` や `categoryId` を BuyInfo Entity に集約する際に、ID の内部の型をそのまま参照しているのが気になりました
https://github.com/hibimosaku/buy-list/blob/master/src/model/buy-info.model.ts#L11-L13

DDD の考え方では、なるべく内部の原始的な型は用いずに、Domain Model の型でデータをやり取りすることが望ましいです

**Comment by hibimosaku** [comment]
理解できました。
修正します。

**Comment by hibimosaku** [comment]
修正しました。
commit名：IDの型修正 issue#9

**Comment by hibimosaku** [comment]
上記のとおり修正しましたので、クローズします。
